
generated_version=0.9.2
# This program depends on some 3rd party softwares to work correctly.

# Kaplas80/ParManager
# Games: Yakuza 3, Yakuza 4, Yakuza 5, Yakuza 6, Judgment, Lost Judgment & Like a Dragon: Ishin!
# required to extract and compile PARC files (.par)
# download at: https://github.com/Kaplas80/ParManager/releases/tag/v1.3.3
partool_root=C:\ParTool.exe

# Luigi Auriemma / QuickBMS
# Games: Ys VIII: Lacrimosa of Dana (Switch)
# required to extract data.dat files
# download at: http://aluigi.altervista.org/papers/quickbms.zip
quickbms_root=

# Ret-HZ/reARMP
# Games: Yakuza 6, Judmgent, Lost Judgment
# required to extract & compile armp files (.bin)
# download at: https://github.com/Ret-HZ/reARMP/releases/tag/v0.11.2
rearmp_root=

# Gildor/umodel
# Games: Like a Dragon: Ishin! & Disaster Report 4
# required to extract & compile .pak files
# download at: https://www.gildor.org/down/47/umodel/umodel_win32.zip
umodel_root=

# akintos/UnrealLocres
# Games: Like a Dragon: Ishin! & Disaster Report 4
# required to extract strings from unreal engine 4 .locres files
# download at: https://github.com/akintos/UnrealLocres/releases/tag/1.1.1
uelocres_root=

# allcoolthingsatoneplace/UnrealPakTool
# Games: Like a Dragon: Ishin! & Disaster Report 4
# required to extract & compile .pak files
# download at: https://github.com/allcoolthingsatoneplace/UnrealPakTool/releases/tag/4.27.0
uepak_root=
